[package]
name = "shite"
version = "0.1.0"
authors = ["jspaulsen <fatiguely@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
nphysics2d = "0.11.1"
nalgebra = "0.18.0"
ncollide2d = "0.19.1"
uuid = { version = "0.7.4", features = ["v4"] }
